apiVersion: v1
kind: Service
metadata:
  name: java-employee-svc
  labels:
    {{- include "java-employee.labels" . | nindent 4 }}
  
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "java-employee.selectorLabels" . | nindent 4 }}
